# 1.- Comprensión de los Datos en Bruto
Vamos a realizar un análisis de los datos que contiene nuestro dataset para ver qué tipo de datos tenemos, a qué clases pertenecen, volumen de datos, valores ausentes, etc.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Variables Globales
retraso = 2             # Indica qué diferencia de años se usa para los cálculos diferenciales
tiempo_prediccion = 2   # Indica con cuantos años de antelación queremos predecir una posible crisis
tiempo_recesion = 4     # Indica cuantos años se consideran como post-crisis y serán eliminados junto
                        # a los años de crisis para evitar sesgo en los datos

## 1.1- Características generales

In [3]:
# Cqrgamos nuestro dataset
data = pd.read_csv('../datasets/JSTdatasetR6.csv', sep=';', na_values='', decimal=',')

# Modificación de parámetros de visualización para que dado que el número de columnas es grande se muestren todas a la vez
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 500)

# Revisamos la tipología de los datos
print('Tipología de atributos:')
display(data.dtypes)

# Revisamos las características de los mismos
print('\n\nCaracteristicas de atributos:')
display(data.describe(include='all'))
display(data.info(show_counts=True))

# Revisamos el número de instancias y atributos
print(f'\n\nVolumetría de datos:\nNúmero de Instancias: {data.shape[0]}\nNúmero de Atributos: {data.shape[1]-1}\n\n')
# Revisamos el número total de países
print(f'Número Total de Países: {len(np.unique(data["iso"]))}')

# Revisamos el número total de años y sus valores
print(f'Número Total de Años: {len(np.unique(data["year"]))}')
print(f'{np.unique(data["year"])}\n\n')

# Mostramos una muestra de los registros
print('Muestra de datos:')
display(data.sample(5))

Tipología de atributos:

year                          int64
country                      object
iso                          object
ifs                           int64
pop                         float64
rgdpmad                     float64
rgdpbarro                   float64
rconsbarro                  float64
gdp                         float64
iy                          float64
cpi                         float64
ca                          float64
imports                     float64
exports                     float64
narrowm                     float64
money                       float64
stir                        float64
ltrate                      float64
hpnom                       float64
unemp                       float64
wage                        float64
debtgdp                     float64
revenue                     float64
expenditure                 float64
xrusd                       float64
tloans                      float64
tmort                       float64
thh                         float64
tbus                        float64
bdebt                       float64
lev                         float64
ltd                         float64
noncore                     float64
crisisJST                   float64
crisisJST_old               float64
peg                         float64
peg_strict                  float64
peg_type                     object
peg_base                     object
JSTtrilemmaIV               float64
eq_tr                       float64
housing_tr                  float64
bond_tr                     float64
bill_rate                   float64
rent_ipolated               float64
housing_capgain_ipolated    float64
housing_capgain             float64
housing_rent_rtn            float64
housing_rent_yd             float64
eq_capgain                  float64
eq_dp                       float64
eq_capgain_interp           float64
eq_tr_interp                float64
eq_dp_interp                float64
bond_rate                   float64
eq_div_rtn                  float64
capital_tr                  float64
risky_tr                    float64
safe_tr                     float64
dtype: object

Caracteristicas de atributos:

,year,country,iso,ifs,pop,rgdpmad,rgdpbarro,rconsbarro,gdp,iy,cpi,ca,imports,exports,narrowm,money,stir,ltrate,hpnom,unemp,wage,debtgdp,revenue,expenditure,xrusd,tloans,tmort,thh,tbus,bdebt,lev,ltd,noncore,crisisJST,crisisJST_old,peg,peg_strict,peg_type,peg_base,JSTtrilemmaIV,eq_tr,housing_tr,bond_tr,bill_rate,rent_ipolated,housing_capgain_ipolated,housing_capgain,housing_rent_rtn,housing_rent_yd,eq_capgain,eq_dp,eq_capgain_interp,eq_tr_interp,eq_dp_interp,bond_rate,eq_div_rtn,capital_tr,risky_tr,safe_tr
count,2718.00000,2718,2718,2718.000000,2667.000000,2666.000000,2664.000000,2561.000000,2.641000e+03,2425.000000,2.666000e+03,2.489000e+03,2.603000e+03,2.603000e+03,2.604000e+03,2.518000e+03,2520.000000,2630.000000,2.050000e+03,1949.000000,2.630000e+03,2489.000000,2.542000e+03,2.561000e+03,2.665000e+03,2.465000e+03,2.312000e+03,1.374000e+03,1.299000e+03,1.865000e+03,2353.000000,2299.000000,2230.000000,2668.000000,2568.000000,2668.000000,2668.000000,2668,2465,2073.000000,2.263000e+03,1909.000000,2295.000000,2351.000000,29.0,5.0,2045.000000,1909.000000,1921.000000,2.170000e+03,2169.000000,7.0,7.0,6.0,2381.000000,2163.000000,1830.000000,1854.000000,2247.000000
unique,NaN,18,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Australia,AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PEG,GBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,151,151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1582,763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1945.00000,NaN,NaN,148.333333,31439.397574,9155.064763,39.793748,42.133609,2.454826e+06,0.188838,4.191118e+01,-4.572271e+04,8.097705e+05,7.925207e+05,1.178995e+06,2.404282e+06,4.677768,5.448643,6.695866e+01,5.484313,4.502840e+01,0.542791,5.041672e+05,5.786972e+05,4.900665e+01,2.879901e+06,1.349183e+06,2.452142e+06,2.862759e+06,3.476208e+06,10.032621,95.857216,36.403978,0.032984,0.035047,0.621439,0.526237,NaN,NaN,-0.002851,1.166184e+06,0.107842,0.059423,0.043779,1.0,1.0,0.060921,0.054374,0.051950,1.167935e+06,0.040949,1.0,1.0,1.0,0.054346,0.042763,0.099308,0.111523,0.051634
std,43.59701,NaN,NaN,24.165940,45898.993728,7976.190143,33.884462,32.274402,1.615548e+07,0.064621,5.689962e+01,7.670287e+05,4.947326e+06,4.956606e+06,1.077840e+07,1.645903e+07,3.332995,3.157725,1.061554e+02,4.081174,7.226900e+01,0.392740,2.952977e+06,3.457500e+06,2.097611e+02,2.143628e+07,1.123262e+07,1.353124e+07,1.550962e+07,2.011087e+07,7.194283,32.326892,19.883801,0.178627,0.183934,0.485119,0.499405,NaN,NaN,0.783131,5.547655e+07,0.104737,0.084800,0.030672,0.0,0.0,0.148323,0.020643,0.020006,5.440622e+07,0.017111,0.0,0.0,0.0,0.031442,0.017694,0.090360,0.110373,0.048357
min,1870.00000,NaN,NaN,111.000000,1675.000000,737.375497,3.263085,4.074400,1.250757e-11,0.017287,1.150362e-11,-1.687900e+07,2.803000e-12,2.278000e-12,1.084000e-12,2.919525e-12,-2.000000,-0.525000,3.014026e-12,0.035923,8.320876e-13,0.019074,5.304000e-13,5.040000e-13,3.610507e-12,3.052196e-12,2.969000e-12,5.540000e-03,2.136998e-01,2.879401e-12,0.848073,11.146478,1.525077,0.000000,0.000000,0.000000,0.000000,NaN,NaN,-3.510000,-8.841469e-01,-0.260873,-0.324742,-0.020000,1.0,1.0,-0.312501,0.004855,0.004855,-8.842261e-01,0.000000,1.0,1.0,1.0,-0.035316,0.000000,-0.232140,-0.238515,-0.152371
25%,1907.00000,NaN,NaN,132.000000,4866.650000,2873.047663,12.694448,15.650000,5.428200e+01,0.140980,2.526395e+00,-6.345947e+01,5.029000e+00,5.110800e+00,9.363653e+00,1.630303e+01,2.627500,3.587708,2.423478e+00,2.300000,4.557921e-01,0.253000,6.933250e+00,6.895100e+00,1.000000e+00,2.123700e+01,8.287246e+00,2.617783e+02,2.907489e+02,1.706697e+02,4.851582,76.823910,19.570512,0.000000,0.000000,0.000000,0.000000,NaN,NaN,-0.165833,-1.370092e-02,0.050949,0.016270,0.027257,1.0,1.0,0.000000,0.039947,0.037467,-5.496224e-02,0.030100,1.0,1.0,1.0,0.036000,0.032112,0.047950,0.051188,0.024857
50%,1945.00000,NaN,NaN,143.000000,10113.530000,5477.011227,23.056114,27.846700,1.810926e+03,0.194356,1.050679e+01,-3.300000e-02,4.873701e+02,4.523997e+02,3.109166e+02,8.713446e+02,4.122500,4.609167,9.883473e+00,4.600000,3.711042e+00,0.447780,2.704400e+02,2.987540e+02,3.709565e+00,1.173430e+03,5.430541e+02,2.622369e+03,3.667680e+03,3.340160e+03,7.505480,94.111916,34.724886,0.000000,0.000000,1.000000,1.000000,NaN,NaN,0.000000,8.600000e-02,0.099381,0.048746,0.039891,1.0,1.0,0.045675,0.050630,0.048504,4.175594e-02,0.040665,1.0,1.0,1.0,0.046100,0.042530,0.090982,0.102568,0.043005
75%,1983.00000,NaN,NaN,172.000000,45077.000000,14619.435708,65.770534,68.720000,5.038345e+04,0.230288,7.617557e+01,1.788000e+01,1.217368e+04,1.040987e+04,1.301771e+04,2.375057e+04,5.758750,6.329375,9.785925e+01,7.524200,7.435417e+01,0.708367,1.035075e+04,1.094400e+04,6.120000e+00,2.769420e+04,1.460649e+04,2.631215e+05,2.503700e+05,1.713124e+05,13.493333,111.880280,51.616881,0.000000,0.000000,1.000000,1.000000,NaN,NaN,0.270000,1.981390e-01,0.152130,0.090038,0.051075,1.0,1.0,0.096386,0.065989,0.063214,1.568719e-01,0.051569,1.0,1.0,1.0,0.063500,0.053196,0.137372,0.159925,0.067896
max,2020.00000,NaN,NaN,193.000000,329239.715278,45887.569802,147.282620,120.431162,2.070466e+08,0.546975,2.268252e+02,5.885998e+06,6.630599e+07,7.237242e+07,2.330690e+08,2.357367e+08,21.273300,23.715415,6.459109e+02,26.093600,3.236591e+02,2.697976,3.602174e+07,4.809886e+07,2.197061e+03,3.111221e+08,1.788609e+08,1.363387e+08,1.747835e+08,2.417130e+08,46.863068,218.164932,84.370613,1.000000,1.000000,1.000000,1.000000,NaN,NaN,4.410750,2.639075e+09,1.363139,0.811297,0.212733,1.0,1.0,2.879476,0.132811,0.130764,2.534419e+09,0.127113,1.0,1.0,1.0,0.237154,0.138189,1.144161,1.281639,0.408514

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2718 entries, 0 to 2717
Data columns (total 59 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   year                      2718 non-null   int64
 1   country                   2718 non-null   object
 2   iso                       2718 non-null   object
 3   ifs                       2718 non-null   int64
 4   pop                       2667 non-null   float64
 5   rgdpmad                   2666 non-null   float64
 6   rgdpbarro                 2664 non-null   float64
 7   rconsbarro                2561 non-null   float64
 8   gdp                       2641 non-null   float64
 9   iy                        2425 non-null   float64
 10  cpi                       2666 non-null   float64
 11  ca                        2489 non-null   float64
 12  imports                   2603 non-null   float64
 13  exports                   2603 non-null   float64
 14  narrowm                   2604 non-null   float64
 15  money                     2518 non-null   float64
 16  stir                      2520 non-null   float64
 17  ltrate                    2630 non-null   float64
 18  hpnom                     2050 non-null   float64
 19  unemp                     1949 non-null   float64
 20  wage                      2630 non-null   float64
 21  debtgdp                   2489 non-null   float64
 22  revenue                   2542 non-null   float64
 23  expenditure               2561 non-null   float64
 24  xrusd                     2665 non-null   float64
 25  tloans                    2465 non-null   float64
 26  tmort                     2312 non-null   float64
 27  thh                       1374 non-null   float64
 28  tbus                      1299 non-null   float64
 29  bdebt                     1865 non-null   float64
 30  lev                       2353 non-null   float64
 31  ltd                       2299 non-null   float64
 32  noncore                   2230 non-null   float64
 33  crisisJST                 2668 non-null   float64
 34  crisisJST_old             2568 non-null   float64
 35  peg                       2668 non-null   float64
 36  peg_strict                2668 non-null   float64
 37  peg_type                  2668 non-null   object
 38  peg_base                  2465 non-null   object
 39  JSTtrilemmaIV             2073 non-null   float64
 40  eq_tr                     2263 non-null   float64
 41  housing_tr                1909 non-null   float64
 42  bond_tr                   2295 non-null   float64
 43  bill_rate                 2351 non-null   float64
 44  rent_ipolated             29 non-null     float64
 45  housing_capgain_ipolated  5 non-null      float64
 46  housing_capgain           2045 non-null   float64
 47  housing_rent_rtn          1909 non-null   float64
 48  housing_rent_yd           1921 non-null   float64
 49  eq_capgain                2170 non-null   float64
 50  eq_dp                     2169 non-null   float64
 51  eq_capgain_interp         7 non-null      float64
 52  eq_tr_interp              7 non-null      float64
 53  eq_dp_interp              6 non-null      float64
 54  bond_rate                 2381 non-null   float64
 55  eq_div_rtn                2163 non-null   float64
 56  capital_tr                1830 non-null   float64
 57  risky_tr                  1854 non-null   float64
 58  safe_tr                   2247 non-null   float64
dtypes: float64(53), int64(2), object(4)
memory usage: 1.2+ MB

None

Volumetría de datos:
Número de Instancias: 2718
Número de Atributos: 58


Número Total de Países: 18
Número Total de Años: 151
[1870 1871 1872 1873 1874 1875 1876 1877 1878 1879 1880 1881 1882 1883
 1884 1885 1886 1887 1888 1889 1890 1891 1892 1893 1894 1895 1896 1897
 1898 1899 1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911
 1912 1913 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925
 1926 1927 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939
 1940 1941 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953
 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967
 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981
 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995
 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009
 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]


Muestra de datos:

,year,country,iso,ifs,pop,rgdpmad,rgdpbarro,rconsbarro,gdp,iy,cpi,ca,imports,exports,narrowm,money,stir,ltrate,hpnom,unemp,wage,debtgdp,revenue,expenditure,xrusd,tloans,tmort,thh,tbus,bdebt,lev,ltd,noncore,crisisJST,crisisJST_old,peg,peg_strict,peg_type,peg_base,JSTtrilemmaIV,eq_tr,housing_tr,bond_tr,bill_rate,rent_ipolated,housing_capgain_ipolated,housing_capgain,housing_rent_rtn,housing_rent_yd,eq_capgain,eq_dp,eq_capgain_interp,eq_tr_interp,eq_dp_interp,bond_rate,eq_div_rtn,capital_tr,risky_tr,safe_tr
1737,1946,Italy,ITA,136,45725.000000,2161.679895,12.200601,12.640000,3.600930e+03,0.209042,3.159149,-144.00000,141.215484,119.944574,814.66,1442.65,4.710000,4.205000,NaN,NaN,0.354856,0.386310,458.921362,825.120607,675.000000,512.161000,38.252000,NaN,NaN,NaN,1.779961,72.264107,37.030830,0.0,0.0,0.0,0.0,FLOAT,USA,NaN,1.601968,0.614544,0.076967,0.047100,NaN,NaN,0.602177,0.012367,0.007719,1.592070,0.003818,NaN,NaN,NaN,0.058500,0.009898,0.585967,0.711815,0.062034
1292,1954,France,FRA,132,43822.000000,5915.179590,25.192009,26.250000,1.645271e+02,0.278020,10.561727,2.58434,15.221000,15.095000,52.98,54.65,3.590000,6.440243,1.156359,2.823333,3.063739,0.343700,33.560000,37.024000,3.740000,56.991708,16.622747,NaN,NaN,NaN,2.833070,52.031212,23.250542,0.0,0.0,0.0,0.0,FLOAT,USA,0.00,1.158557,0.207008,0.090020,0.035900,NaN,NaN,0.136628,0.070380,0.061920,1.119145,0.018598,NaN,NaN,NaN,0.064402,0.039412,0.296905,0.379779,0.062960
925,1889,Spain,ESP,184,17591.188933,1547.013355,9.014399,12.059242,8.712307e+03,0.052505,0.272246,-42.80000,806.834915,891.242448,2273.00,2443.00,3.500000,5.280000,NaN,NaN,0.048480,0.790032,761.000000,833.000000,5.338346,NaN,NaN,NaN,NaN,NaN,26.397940,113.239059,62.875599,0.0,0.0,0.0,0.0,FLOAT,GBR,0.00,NaN,NaN,NaN,0.035000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.052800,NaN,NaN,NaN,NaN
251,1970,Belgium,BEL,124,9651.000000,10610.824047,47.810263,47.357700,1.281000e+06,0.224746,31.507332,36200.00000,570600.000000,580000.000000,392200.00,NaN,7.860000,7.810000,24.246849,1.731360,19.627977,0.474919,300145.000000,351759.000000,49.675000,730900.000000,217000.000000,298618.1563,432281.8438,544936.8125,5.304958,101.857391,43.809277,0.0,0.0,1.0,1.0,PEG,USA,-0.78,0.051439,NaN,0.064807,0.078600,1.0,NaN,-0.010674,NaN,NaN,-0.001291,0.052799,NaN,NaN,NaN,0.078100,0.052731,NaN,NaN,0.071704
165,1884,Belgium,BEL,124,5807.000000,3136.104873,11.581146,NaN,5.049432e+03,NaN,0.648618,-166.09974,1109.367490,943.267750,1581.80,NaN,3.272603,3.560000,0.359355,NaN,0.285642,0.350141,306.000000,362.000000,5.140000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,1.0,PEG,GBR,-0.63,-0.034098,NaN,0.061599,0.034561,NaN,NaN,-0.218934,NaN,NaN,-0.081247,0.051319,NaN,NaN,NaN,0.035600,0.047149,NaN,NaN,0.048080

In [4]:
# Revisamos la distribución de los valores ausentes
num_ausentes = data.isna().sum()
porcentaje = round(num_ausentes / data.shape[0] * 100, 2)
porcentaje.sort_values(ascending=False, inplace=True)
porcentaje_med = round(np.sum(porcentaje) / porcentaje.shape[0], 2)
print(f'Porcentaje Medio de Valores Ausentes: {porcentaje_med}%\n')
print('Porcentaje de Valores Ausentes por Columna')
print(porcentaje)

Porcentaje Medio de Valores Ausentes: 20.46%

Porcentaje de Valores Ausentes por Columna
housing_capgain_ipolated    99.82
eq_dp_interp                99.78
eq_tr_interp                99.74
eq_capgain_interp           99.74
rent_ipolated               98.93
tbus                        52.21
thh                         49.45
capital_tr                  32.67
risky_tr                    31.79
bdebt                       31.38
housing_rent_rtn            29.76
housing_tr                  29.76
housing_rent_yd             29.32
unemp                       28.29
housing_capgain             24.76
hpnom                       24.58
JSTtrilemmaIV               23.73
eq_div_rtn                  20.42
eq_dp                       20.20
eq_capgain                  20.16
noncore                     17.95
safe_tr                     17.33
eq_tr                       16.74
bond_tr                     15.56
ltd                         15.42
tmort                       14.94
bill_rate                   13.50
lev                         13.43
bond_rate                   12.40
iy                          10.78
peg_base                     9.31
tloans                       9.31
debtgdp                      8.43
ca                           8.43
money                        7.36
stir                         7.28
revenue                      6.48
rconsbarro                   5.78
expenditure                  5.78
crisisJST_old                5.52
exports                      4.23
imports                      4.23
narrowm                      4.19
ltrate                       3.24
wage                         3.24
gdp                          2.83
rgdpbarro                    1.99
xrusd                        1.95
cpi                          1.91
rgdpmad                      1.91
pop                          1.88
peg_type                     1.84
peg_strict                   1.84
crisisJST                    1.84
peg                          1.84
country                      0.00
ifs                          0.00
iso                          0.00
year                         0.00
dtype: float64

Como se puede observar hay atributos con un número elevado de valores ausentes. Antes de continuar y para ver si todas las instancias del dataset serán útiles, vamos a revisar la distribución temporal de dichos valores ausentes.

Estableceremos como primer criterio de filtrado, que únicamente se utilizará la información correspondiente a las instancias con un número total de valores ausentes inferior al 25% del total del número de atributos. De manera adicional, se usará únicamente la serie temporal contigua con un número de instancias útiles superior también al 25% del número total de países por año, es decir, sólo se usarán los años contiguos en los que todos garanticen los dos criterios anteriores:

In [5]:
# Obtenemos el número de muestras de países por año para el primer criterio
# (número total de valores ausentes inferior al 30%)

th_atributos = data.shape[1]*30/100
datos_agrupados = data.groupby('year').apply(lambda x: (x.isnull().sum(axis=1) > th_atributos).sum())
print(pd.Series(datos_agrupados, name='Muestras Inválidas'))

# Calculamos la serie de años final que cumple tanto el primer criterio como el segundo:
th_anios = len(np.unique(data["iso"]))*30/100
ultimo_anio_no_util = datos_agrupados[::-1].gt(th_anios).idxmax()
print(f'Años útiles: {np.unique(data[data["year"]>ultimo_anio_no_util]["year"])}')

year
1870    18
1871    13
1872    14
1873    14
1874    14
1875    13
1876    13
1877    13
1878    13
1879    13
1880    11
1881    11
1882    11
1883    11
1884    11
1885    10
1886    10
1887    10
1888    10
1889    10
1890     9
1891     9
1892     9
1893     8
1894     8
1895     8
1896     8
1897     8
1898     8
1899     8
1900     4
1901     4
1902     4
1903     4
1904     4
1905     4
1906     4
1907     4
1908     4
1909     4
1910     4
1911     4
1912     4
1913     3
1914     4
1915     7
1916     7
1917     7
1918     7
1919     7
1920     4
1921     4
1922     3
1923     3
1924     3
1925     2
1926     2
1927     2
1928     2
1929     2
1930     2
1931     2
1932     2
1933     2
1934     2
1935     2
1936     3
1937     3
1938     3
1939     4
1940     5
1941     4
1942     5
1943     5
1944     5
1945     7
1946     5
1947     5
1948     3
1949     3
1950     2
1951     2
1952     2
1953     2
1954     2
1955     2
1956     2
1957     2
1958     2
1959     2
1960     2
1961     2
1962     2
1963     2
1964     2
1965     2
1966     2
1967     2
1968     2
1969     2
1970     2
1971     2
1972     2
1973     2
1974     2
1975     2
1976     2
1977     2
1978     2
1979     2
1980     2
1981     2
1982     2
1983     2
1984     2
1985     2
1986     2
1987     2
1988     2
1989     2
1990     2
1991     2
1992     2
1993     2
1994     2
1995     2
1996     2
1997     2
1998     2
1999     2
2000     2
2001     2
2002     2
2003     2
2004     2
2005     2
2006     2
2007     2
2008     2
2009     2
2010     2
2011     2
2012     2
2013     2
2014     2
2015     2
2016     2
2017     2
2018     2
2019     2
2020     2
Name: Muestras Inválidas, dtype: int64
Años útiles: [1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959
 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973
 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987
 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001
 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015
 2016 2017 2018 2019 2020]

Eliminamos las instancias no útiles y revisamos las volumetrías finales:

In [6]:
data.drop(data[data['year'] <= ultimo_anio_no_util-retraso].index, inplace=True)
data = data.reset_index(drop=True)

In [7]:
# Revisamos el número de instancias y atributos
print(f'\n\nVolumetría de datos:\nNúmero de Instancias: {data.shape[0]}\nNúmero de Atributos: {data.shape[1]-1}\n\n')
# Revisamos el número total de países
print(f'Número Total de Países: {len(np.unique(data["iso"]))}')

# Revisamos el número total de años y sus valores
print(f'Número Total de Años: {len(np.unique(data["year"]))}')
print(f'{np.unique(data["year"])}\n\n')

clases, ocurrencias = np.unique(data['crisisJST'], return_counts=True)
etiquetas = ['No Crisis', 'Crisis']
porcentajes = np.round(ocurrencias / data.shape[0] * 100, 2)
print(f'Clases: {clases}\nEtiquetas {etiquetas}\nOcurrencias: {ocurrencias}\nPorcentajes {porcentajes}')

Volumetría de datos:
Número de Instancias: 1386
Número de Atributos: 58


Número Total de Países: 18
Número Total de Años: 77
[1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957
 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971
 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985
 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999
 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013
 2014 2015 2016 2017 2018 2019 2020]


Clases: [0. 1.]
Etiquetas ['No Crisis', 'Crisis']
Ocurrencias: [1361   25]
Porcentajes [98.2  1.8]

## Conclusiones Previas
Como puntos a descatar sobre nuestro dataset:
* Existe un acusado desbalance de instancias asociadas a cada clase
* El volumen de valores ausentes era elevado en algunos atributos y hemos tenido que realizar un primer filtrado de datos brutos útiles.
* Debemos trabajar con datos asociados a series temporales.

# 2.- Preparación de Dataset
A partir de los datos anteriores se procede a la elaboración de los siguientes nuevos atributos que serán los finalmente usados como base para el proceso de entrenamiento:
+ Diferencial relativo del Índice de Precios al Consumo.
+ Diferencial absoluto del Agregado Monetario Amplio (M3) escalado por el Producto Interior Bruto del país.
+ Diferencial relativo del Consumo Real per Cápita.
+ Diferencial absoluto del volumen de Deuda Pública escalado por el Producto Interior Bruto.
+ Diferencial absoluto del volumen de Inversión escalado por el Producto Interior Bruto.
+ Diferencial absoluto del estado de Cuenta Corriente del país escalado por el Producto Interior Bruto.
+ Diferencial absoluto del Volumen de Crédito al sector privado escalado por el Producto Interior Bruto.
+ Diferencial absoluto del ratio Volumen de Crédito al sector privado - Tipo de Interés a largo plazo.
+ Aumento de Crédito Global.
+ Curva de Rendimiento Global (Global Yield Curve).
+ Ratio Tipos de Interes a Largo Plazo vs Corto Plazo.

In [8]:
# Funciones auxiliares

def crear_atributos_escalados_pib(data, atributos):
    # Escalamos los atributos de entrada dividiendo su valor por el 'Gross Domestic Product'
    atributos_escalados = []
    for atributo in atributos:
        nombre = f'{atributo}_pib'
        data[nombre] = data[atributo] / data['gdp']
        atributos_escalados.append(nombre)
    return data, atributos_escalados


def calcula_atributos_diferenciales(data, atributos, tipo, retraso=2):
    # Variables calculadas como el diferencial absoluto o porcentual entre el 
    # valor actual de la variable y el asociado 'retraso' años atrás
    for atributo in atributos:
        if tipo == 'absoluto': # Diferencial Absoluto
            nombre = f'{atributo}_dif_abs{retraso}'
            data[nombre] = data.groupby('iso', group_keys=False)[atributo].diff(retraso)
        else: # Diferencial Porcentual
            nombre = f'{atributo}_dif_por{retraso}'
            data[nombre] = data.groupby('iso', group_keys=False)[atributo].apply(lambda x: cambio_relativo_historico(x, retraso))
    return data


def cambio_relativo_historico(atributo, retraso):
    # Calcula el cambio relativo para un atributo entre dos fechas 
    atributo_historico = np.array(atributo.shift(retraso))
    return (atributo - atributo_historico) / atributo_historico


def marca_pre_post_crisis(data):
    # Buscamos los años de crisis
    posiciones = data[data['crisisJST'] == 1].index
    data[data['crisisJST'] == 1].to_csv('../datasets/finales/test3.csv', sep=';', na_rep='', decimal=',', index=False)
    aux = data['crisisJST'].copy()
    for posicion in posiciones:
        # Cambiamos la clase de las intancias de crisis para borrarlas posteriormente
        aux[posicion] = 2

        # Marcamos las instancias post-crisis (importante comprobar límites de dataframe y que se mantiene
        # el mismo país)
        for j in range(posicion + 1, posicion + tiempo_recesion + 1):
            if not j >= data.shape[0]:
                if data['iso'][j] == data['iso'][posicion]:
                    aux[j] = 2
        # Marcamos las instancias pre-crisis (importante comprobar límites de dataframe y que se mantiene
        # el mismo país)
        for j in range(posicion - 1, posicion - tiempo_prediccion - 1, -1):
            if not j < 0:
                if data['iso'][j] == data['iso'][posicion]:
                    aux[j] = 1
    data['crisisJST'] = aux
    return data

def aumento_credito_global(data):
    for year in data['year'].unique():
        for country in data['iso'].unique():
                # El calculo se realiza para cada año teniendo en cuenta todos
                # los países menos el actual
            perc_pos = data.loc[(data['year']==year) & (data.iso != country), 'tloans_pib_dif_abs' + str(retraso)].mean()
            if not np.isnan(perc_pos):
                data.loc[(data['year']==year) & (data.iso == country), 'global_loan' + str(retraso)] = perc_pos
    return data


def pendiente_curva_yield_global(data):
    for year in data["year"].unique():
        for country in data["iso"].unique():
                # El calculo se realiza para cada año teniendo en cuenta todos
                # los países menos el actual
            perc_pos = data.loc[(data['year']==year) & (data.iso != country), "drate"].mean()
            if not np.isnan(perc_pos):
                data.loc[(data['year']==year) & (data.iso == country), "global_drate"] = perc_pos
    return data


def crear_dataset(df):
    # Creación del dataset de trabajo a partir de los datos en bruto
    data = df.copy()

    # Cálculo de atributos finales
    data.loc[:, 'drate'] = data['ltrate'] - data['stir']  # Rate Diferencial
    data.loc[:, 'pdebt'] = data['debtgdp'] * data['gdp']  # Deuda Pública neta
    data.loc[:, 'inv'] = data['iy'] * data['gdp']         # Inversión neta
    data.loc[:, 'tdbtserv'] = data['tloans'] * data['ltrate'] / 100.0    # Ratio Volumen de Crédito al sector privado - Tipo de Interés a largo plazo

        # Atributos a escalar por el PIB del país (GDP)
    atributos_escalar = ['money', 'narrowm', 'tloans', 'tbus',
                          'thh', 'tmort', 'ca', 'cpi', 'tdbtserv',
                          'inv', 'pdebt']
    
    data, atributos_escalados_pib = crear_atributos_escalados_pib(data, atributos_escalar)
    
        # Atributos calculados por diferenciales entre años

            # Diferencias absolutas    
    data = calcula_atributos_diferenciales(data, ['ltrate', 'stir', 'drate'] + atributos_escalados_pib, 'absoluto', retraso)

            # Diferencias relativas
    data = calcula_atributos_diferenciales(data, ['hpnom', 'rconsbarro', 'gdp'] + atributos_escalar, 'porcentaje', retraso=retraso)
    
        # Atributos calculados mediante indicadores globales

    data = aumento_credito_global(data)
    
    data = pendiente_curva_yield_global(data)

    # Marcado de años precrisis, post-crisis
    
    data = marca_pre_post_crisis(data)
    
    # Nos quedamos sólo con las columnas necesarias
    atributos_finales = ['cpi_dif_por2', 'money_pib_dif_abs2', 'rconsbarro_dif_por2',
                         'pdebt_pib_dif_abs2', 'inv_pib_dif_abs2', 'ca_pib_dif_abs2',
                         'tloans_pib_dif_abs2', 'tdbtserv_pib_dif_abs2', 'global_loan2',
                         'global_drate', 'drate']

    data = pd.concat([data.loc[:, atributos_finales], data['year'], data['iso'], data['crisisJST']], axis=1)

    # Eliminamos los años de crisis y post-crisis para evitar sesgo en los datos
    data.drop(data[data.crisisJST == 2].index, inplace=True)

    data.drop(data[data['year'] <= ultimo_anio_no_util].index, inplace=True)
    
    # Ordenamos el dataset por año y país para facilitar posteriormente el particionado
    # evitando el leak de datos temporales entre entrenamiento y test
    data.sort_values(by=['year', 'iso'], inplace=True)
        
    data = data.reset_index(drop=True)  # update index
    return data

In [9]:
# Creamos el dataset de trabajo
data = crear_dataset(data)
print(data['year'].unique())

[1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959
 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973
 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987
 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001
 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015
 2016 2017 2018 2019 2020]

## Guardamos el dataset creado

In [10]:
import os
if not os.path.exists('../datasets/finales'):
    os.mkdir('../datasets/finales')

data.to_csv('../datasets/finales/data_final.csv', sep=';', na_rep='', decimal=',', index=False)